name: dev-release

on:
  pull_request:
    branches:
      - dev # PRs targeting /dev
    types:
      - closed

jobs:
  check-and-publish-dev-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to compare with previous commit

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Get published version from npm
        id: prev
        run: |
          VERSION=$(npm view h1z1-server@next version)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Read current version from package.json
        id: current
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Compare versions
        id: compare
        run: |
          if [ "${{ steps.prev.outputs.version }}" != "${{ steps.current.outputs.version }}" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if new version is prerelease
        id: prerelease
        run: |
          VERSION=${{ steps.current.outputs.version }}
          if [[ "$VERSION" == *-* ]]; then
            echo "isprerelease=true" >> $GITHUB_OUTPUT
          else
            echo "isprerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if base version (x.y.z) is unchanged
        id: basecheck
        run: |
          prev_base=$(echo "${{ steps.prev.outputs.version }}" | cut -d'-' -f1)
          curr_base=$(echo "${{ steps.current.outputs.version }}" | cut -d'-' -f1)

          echo "Previous base version: $prev_base"
          echo "Current base version: $curr_base"

          if [ "$prev_base" = "$curr_base" ]; then
            echo "base_unchanged=true" >> $GITHUB_OUTPUT
          else
            echo "base_unchanged=false" >> $GITHUB_OUTPUT
          fi

      - name: Ensure version changed and is valid prerelease
        if: steps.compare.outputs.changed == 'true' && steps.prerelease.outputs.isprerelease == 'true' && steps.basecheck.outputs.base_unchanged == 'true'
        run: echo "Ready to publish..."

      - name: Publish to npm
        if: steps.compare.outputs.changed == 'true' && steps.prerelease.outputs.isprerelease == 'true' && steps.basecheck.outputs.base_unchanged == 'true'
        run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
